-- Run this entire block in Supabase Dashboard → SQL Editor
-- https://supabase.com/dashboard/project/qxhqoczzdnijlairmueq/editor

alter table outfit_item add column if not exists description text;

update outfit_item set description = case name
  when 'Geobasket Sneakers' then 'The iconic Rick Owens basketball sneaker with exaggerated platform sole. Hand-stitched leather upper, asymmetric lacing, signature elongated toe. A design icon since 2014.'
  when 'Geobasket Pearl' then 'Geobasket in off-white pearl leather. The rarest colorway — clean, sculptural, impossible to ignore. Platform sole adds 5cm height.'
  when 'Geobasket Black' then 'Geobasket in full black leather. The most versatile colorway — pairs with any dark look. Platform sole, hand-stitched, made in Italy.'
  when 'Geobasket Milk' then 'Geobasket in milk white with contrasting black sole. The definitive light colorway of the most iconic dark luxury sneaker.'
  when 'DRKSHDW Mega T-Shirt' then 'Oversized cotton jersey tee with dropped shoulders and raw-edge hem. The foundation of any DRKSHDW look — wear alone or layered under an open shirt.'
  when 'Pod Shorts' then 'Rick Owens signature pod silhouette in heavy cotton. Balloon shape, elasticated waist, falls below the knee. Pairs with everything in the dark wardrobe.'
  when 'Leather Biker Jacket' then 'Rick Owens asymmetric zip biker in lamb leather. Buttery soft, structured shoulders, signature dark hardware. The jacket that started a thousand imitations.'
  when 'Tecuatl Cargo Pods' then 'Named after the Aztec god of war — cargo trousers with exaggerated pod pockets and dropped crotch. Heavy cotton, elasticated waist, Rick Owens at his most architectural.'
  when 'Ramones Low Sneakers' then 'Rick Owens punk-influenced low sneaker. Named after the band. Crepe sole, leather upper, minimal branding. The entry point to the Rick footwear universe.'
  when 'White Draped Tunic' then 'Rick Owens white draped tunic — rare and pure. The dark lord in white. Oversized, draped, floor-length. Architectural simplicity.'
  when 'White Pod Trousers' then 'Rick Owens white pod trousers. The pod silhouette in white — maximum visual impact, zero compromise.'
  when 'White Geobasket Sneakers' then 'Geobasket in full white leather. The holy grail colorway. Almost impossible to keep clean — that is part of the appeal.'
  when 'Elongated Dropped Shoulder Coat' then 'Rick Owens Creatch silhouette coat — dropped shoulders create an inhuman width, length hits mid-calf. The most architectural coat in dark luxury.'
  when 'Creatch Trousers' then 'Rick Owens Creatch trousers with extreme dropped crotch and tapered leg. Named after the creature-like silhouette they create.'
  when 'Dunks Collab Sneakers' then 'Rick Owens x Nike Dunk collab — classic basketball silhouette filtered through the Rick Owens lens. Dark colorways, premium leather, instant classic.'
  when 'Tabi Split-Toe Boots' then 'Maison Margiela most iconic piece — the split-toe boot inspired by Japanese tabi socks. Leather upper, block heel, invisible back zip. Been in continuous production since 1988.'
  when 'Deconstructed Blazer' then 'Margiela blazer with exposed lining, raw edges and visible construction. Anti-fashion at its finest — a blazer that shows you exactly how it was made.'
  when 'Straight Trousers' then 'Margiela clean-cut straight leg trousers. No branding, no excess. Worn with the Tabi boot they create the definitive Margiela silhouette.'
  when 'MM6 Replica Sneakers' then 'Maison Margiela Replica — exact recreation of a 1970s German Army trainer. Canvas upper, gum sole, vintage feel. The most wearable Margiela shoe.'
  when 'Layered Hoodie' then 'MM6 deconstructed hoodie with asymmetric hem and raw edges. Looks like two hoodies — is actually one. That is the Margiela way.'
  when 'Destroyed Denim' then 'Margiela selvedge denim with deliberate distressing and fading. Each pair unique. Worn slim, cuffed above the Replica sneaker.'
  when 'Raw-Edge Overcoat' then 'Margiela Number 0 overcoat — raw edges, exposed seams, stitched number label on the back. The Margiela manifesto in coat form.'
  when 'Grey Tailored Trousers' then 'Margiela grey tailored trousers. No label visible. Just perfect tailoring — the anonymous luxury.'
  when 'Tabi Low Boots' then 'Margiela Tabi in low boot form. The split toe in its most wearable format — easier to style than the heel but just as iconic.'
  when 'MM6 Future Zip Hoodie' then 'MM6 Maison Margiela future zip hoodie with off-center zip and structured shoulders. Deconstructed sportswear from the Margiela diffusion line.'
  when 'Cargo Trousers External Pockets' then 'MM6 cargo trousers with external pocket construction. The pockets sit on the outside — Margiela showing you exactly how clothes are made.'
  when 'Japanese Collab Sneakers' then 'MM6 x Japanese brand collab sneaker. Limited run, clean design, collector piece.'
  when 'Triple S Sneakers' then 'Balenciaga Triple S — three soles stacked for maximum height and maximum statement. Dad shoe taken to its logical extreme. Still the most recognisable chunky sneaker ever made.'
  when 'Oversized Hoodie' then 'Balenciaga political hoodie in heavyweight fleece. Fits three sizes up by design. Pull the sleeves down, let it drop — that is the Demna silhouette.'
  when 'Track Pants' then 'Balenciaga technical track pants with side stripe and tapered leg. Pairs with Triple S for the complete luxury athleisure look.'
  when 'Knife Boots' then 'Balenciaga Knife boots with extreme pointed toe — so sharp they look dangerous. Cuban heel, leather upper, the most dramatic boot in luxury fashion.'
  when 'Technical Coat' then 'Balenciaga technical coat in structured fabric. Demna architecture — sharp shoulders, precise cut, impossible volume.'
  when 'Slim Trousers' then 'Balenciaga slim trousers in technical fabric. Clean line from waist to ankle. Worn with Knife boots for the complete Demna look.'
  when 'Speed Sock Boot Sneaker' then 'Balenciaga Speed — the sock sneaker that changed footwear. No laces, no tongue, just a sock with a sole. Instant icon from 2017.'
  when 'Destroyed Balenciaga Hoodie' then 'Balenciaga destroyed hoodie — intentional distressing, political commentary, luxury decay. Demna making a point about fast fashion by destroying slow fashion.'
  when 'Ripped Jeans' then 'Balenciaga ripped jeans — extreme distressing, luxury denim. Costs more destroyed than most jeans cost intact. That is the point.'
  when 'Slim Black Denim' then 'Saint Laurent skinny jeans in raw black denim. The Hedi Slimane cut — impossibly slim, sits low on the hip. Rock and roll in denim form.'
  when 'Chelsea Boots' then 'Saint Laurent Cuban heel chelsea boot in black leather. The essential rock shoe — worn by everyone from the Rolling Stones to Hedi models.'
  when 'Destroyed Skinny Jeans' then 'Saint Laurent destroyed skinny jeans — Hedi Slimane vision of rock and roll. Extremely slim, extremely destroyed, extremely Saint Laurent.'
  when 'Band Tee' then 'Saint Laurent band tee in vintage wash cotton. Worn slim, tucked into the skinny jeans. Rock and roll luxury at its most distilled.'
  when 'Saint Laurent Ankle Boots' then 'Saint Laurent ankle boots with Cuban heel and pointed toe. The rock boot — worn by every SLP devotee since the Hedi era.'
  when 'Oversized Black Coat' then 'Yohji Yamamoto oversized wool coat with dropped shoulders and floor-grazing length. Wabi-sabi in coat form — imperfect, poetic, entirely black.'
  when 'Wide Trousers' then 'Yohji Yamamoto wide-leg trousers in heavy crepe. The volume balances the oversized coat above. Worn with flat shoes for maximum architectural effect.'
  when 'Crepe Shirt' then 'Yohji Yamamoto asymmetric crepe shirt with one longer panel. Worn untucked, partially tucked, or tied at the waist. No wrong way.'
  when 'Kimono Jacket' then 'Yohji Yamamoto kimono-influenced jacket in heavy black wool. East meets West in the most poetic way — structured shoulders, flowing body.'
  when 'Asymmetric Shirt' then 'Yohji Yamamoto asymmetric shirt with one longer panel and off-center placket. Poetry in cotton.'
  when 'Y-3 Technical Jacket' then 'Y-3 (Yohji Yamamoto x Adidas) technical jacket. Where Japanese fashion philosophy meets German sportswear engineering. The best of both worlds.'
  when 'Y-3 Cargo Trousers' then 'Y-3 cargo trousers with Adidas stripe and Yohji volume. Sport and poetry in one trouser.'
  when 'Y-3 Qasa Sneakers' then 'Y-3 Qasa high — the sock-like sneaker that launched a thousand imitations. Elasticated ankle, minimal branding, Japanese precision.'
  when 'Padded Distortion Jacket' then 'Comme des Garcons Homme Plus jacket with padded inserts that distort the body shape. Rei Kawakubo war on conventional beauty — lumps and bumps as design.'
  when 'Wide Structured Trousers' then 'CDG structured wide trousers that hold their shape without a body inside. Architecture you wear.'
  when 'CDG Salomon Collab' then 'Comme des Garcons x Salomon XT-6. Trail running shoe meets Tokyo conceptualism. One of the best collab sneakers ever made.'
  when 'CDG Play Heart Tee' then 'The most recognisable Comme des Garcons piece — white tee with Filip Pagowski hand-drawn heart. Simple, iconic, endlessly wearable.'
  when 'Slim Black Trousers' then 'CDG Play slim trousers in black cotton. The foundation for the heart tee. Clean, minimal, Japanese.'
  when 'Converse CDG Chuck Taylor' then 'Comme des Garcons x Converse Chuck Taylor with the Play heart on the ankle. The most accessible CDG piece and the most worn.'
  when 'Mesh Architectural Knit' then 'Noir Kei Ninomiya mesh knit with architectural structure — 3D construction that holds its form off the body. Dark tech meets Japanese craft.'
  when 'Black Structured Trousers' then 'Noir Kei Ninomiya structured trousers in heavy black fabric. The structure is internal — no visible boning, just perfect engineering.'
  when 'Salomon XT-6 CDG' then 'Comme des Garcons x Salomon XT-6 trail runner. The best trail shoe meets the most conceptual fashion house. Instant classic.'
  when 'Draped Linen Shirt' then 'Ann Demeulemeester draped linen shirt with asymmetric hem. Belgian romanticism in fabric form — looks effortless, takes years to design.'
  when 'Lace-Up Leather Boots' then 'Ann Demeulemeester lace-up boots with stacked heel. The definitive Belgian boot — worn by artists, musicians, and anyone who understands dark romanticism.'
  when 'Heeled Ankle Boots' then 'Ann Demeulemeester heeled ankle boots with pointed toe and Cuban heel. The essential dark romantic shoe.'
  when 'Poet Shirt' then 'Ann Demeulemeester romantic poet shirt in white cotton with lace details. Dark romanticism meets 18th century — worn with black everything.'
  when 'Bondage Strap Jacket' then 'Helmut Lang archive reissue jacket with bondage straps across the torso. New York 1998 — industrial minimalism at its peak.'
  when 'Slim Tailored Trousers' then 'Helmut Lang slim tailored trousers. Clean, precise, minimal. The antidote to excess — just good tailoring.'
  when 'Industrial Boots' then 'Helmut Lang industrial lace-up boots with thick rubber sole. Utilitarian but luxurious — the Lang paradox in shoe form.'
  when 'Minimal Cotton Shirt' then 'Helmut Lang minimal cotton shirt with precise cut and no excess. Just a perfect shirt. That is the Lang way.'
  when 'Tailored Trousers' then 'Helmut Lang tailored trousers in grey wool. Quiet luxury before quiet luxury was a trend.'
  when 'Classic Derby Shoes' then 'Clean leather derby shoes. Minimal, precise, Helmut Lang.'
  when 'Oversized Parka with Patches' then 'Raf Simons archive parka covered in embroidered patches referencing youth culture, music, and Belgian art. Every patch tells a story.'
  when 'Slim Jeans' then 'Raf Simons slim jeans in raw selvedge denim. Belgian youth culture in denim form — worn with the parka for the full Antwerp look.'
  when 'Adidas Raf Simons Sneakers' then 'Raf Simons x Adidas — the collab that changed sneaker culture. Oversized tongue, archive colorways, Belgian precision meets German engineering.'
  when 'Archive Bomber Jacket' then 'Raf Simons archive bomber with youth culture references and precise tailoring. The jacket that made Antwerp fashion school famous.'
  when 'Adidas Raf Simons Ozweego' then 'Raf Simons x Adidas Ozweego — chunky silhouette, multi-material upper, futuristic sole. The blueprint for every dad shoe that followed.'
  when 'Layered Technical Jacket' then 'Julius post-apocalyptic technical jacket with multiple zips, pockets and attachment points. Designed for a world after collapse — or just Tokyo.'
  when 'Drop Crotch Trousers' then 'Julius drop-crotch trousers in technical fabric. The silhouette is exaggerated, the construction precise. Dark luxury from Japan most extreme brand.'
  when 'Platform Creeper Boots' then 'Julius platform creeper boots with extreme sole height. Post-apocalyptic footwear for the fashion forward. Not for the faint-hearted.'
  when 'Pleated Top' then 'Issey Miyake Pleats Please top in permanent pleats. Machine washable, wrinkle-free, packs into nothing. Technology as fashion.'
  when 'Pleated Trousers' then 'Issey Miyake Pleats Please wide-leg trousers. The pleats expand and contract with movement — geometry in motion. Available in 30+ colorways.'
  when 'Flat Mules' then 'Clean leather mules to complete the Pleats Please look. Minimal, functional, Japanese.'
  when 'Undercover Archival Graphic Tee' then 'Undercover archival graphic tee from Jun Takahashi most referenced collections. Punk imagery, Japanese precision, hand-screen printed graphics.'
  when 'Nike Undercover Collab Sneakers' then 'Nike x Undercover collab — Jun Takahashi punk sensibility applied to Nike running. One of the most coveted Nike collabs ever.'
  when 'Raw Edge Wool Coat' then 'Undercover raw edge wool coat from the AW collection. Unfinished hems, asymmetric panels, dark academic energy. Tokyo meets London punk.'
  when 'Layered Knit' then 'Undercover layered knit that looks like two sweaters in one. Heavy wool, dropped shoulders, slightly cropped. Chaos and balance.'
  when 'Military Deconstructed Jacket' then 'Undercover military jacket with deconstructed details — exposed lining, raw edges, recontextualised insignia. Anti-militarism as fashion.'
  when 'Slim Technical Trousers' then 'Undercover slim technical trousers with zip details and articulated knees. Function meets Tokyo street style.'
  when 'Gyakusou Collab Runners' then 'Nike x Undercover Gyakusou running shoe — designed for actual running but worn everywhere. The most technical collab in Undercover history.'
  else description
end
where description is null or description = '';
